wb_control:
  ros__parameters:

    solver:
      horizon_steps: 100
      dt: 0.01

    weights:
      swing_goal: 10000.0
      state_reg: 0.1
      control_reg: 0.0001
      state_limits: 1000.0
      control_limits: 1000.0
