mlivr_wbc:
  ros__parameters:

    solver:
      horizon_steps: 1000
      dt: 0.01
      max_iter: 1000

    weights:
      state_reg: 1e-2
      control_reg: 1e-2

      state_limits: 1e-2
      control_limits: 1e-2

      ee_tracking: 5e1
      sup_ee_tracking: 5e1
      ee_vel_damping: 1e0

      env_collision: 1e1

      momentum_reg: 0.0
